__default__:
    "n": 1
    "memory": 2000
    "qos": "1hr"
    "time": "1:00:00"
cutadapt:
    "n": 5
bwa_index:
    "n": 1
    "qos": "1day"
    "time": "6:00:00"
    "memory": 10000
bwa_aln:
    "n": 10
    "qos": "1day"
    "time": "6:00:00"
    "memory": 50000
bwa_samse:
    "n": 10
    "qos": "1day"
    "time": "6:00:00"
    "memory": 50000
