genome_dir: "genome"
genome: "chrM"
annot_file: "chrM"
sample_dir: "data"
samples:
    - "T2_1"
    - "T2_2"
    - "WT_1"
    - "WT_2"
offset: 14
min_length: 15
max_length: 45
mapping_function: threeprime
