# Pattern to input fastq files, use {sample} to indicate portion of filename
# that corresponds to the sample name (e.g. data/{sample}.fq.gz)
fastq_file_pattern: "data/fastq/{sample}.fastq.gz"


# Genome reference files

# The genome reference sequence in fasta format
genome_fasta_ftp: "ftp://ftp.ensembl.org/pub/release-100/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa.gz"
genome_fasta_file: "genome/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa.gz"

# The gene annotations in GFF v3 format
genome_annotation_gff3_ftp: "ftp://ftp.ensembl.org/pub/release-100/gff3/homo_sapiens/Homo_sapiens.GRCh38.100.gff3.gz"
genome_annotation_gff3_file: "genome/Homo_sapiens.GRCh38.100.gff3.gz"
genome_annotation_gtf_ftp: "ftp://ftp.ensembl.org/pub/release-100/gtf/homo_sapiens/Homo_sapiens.GRCh38.100.gtf.gz"
genome_annotation_gtf_file: "genome/Homo_sapiens.GRCh38.100.gtf.gz"

# Mitochondrial Chromosome ID
mito_chrom_id: "MT"

# Gene ID to use to determine p-site offset (using CDS Start) 
# By default, we selected ATP6 since there is a 5' UTR
start_site_gene_id: "ENSG00000198899"

# Gene ID to use to determine a-site offset (using CDS Stop) 
# By default, we selected ND6 since there is a 3' UTR
stop_site_gene_id: "ENSG00000198695"

# Generate summary counts for gene biotypes
biotype_summary_counts: False
# Categories for each gene_biotype for summary statistics
biotype_categories: "genome/biotype_categories.txt"

# Other genome information files
# **TODO** Add file format infomation
mito_aminoacid_codon: "genome/AA_Codon_HumMito.csv"
mito_info: "genome/Mito_GeneInfo.txt"


# Output directories
# Directory to put working files (trimmed reads, bam files, etc.)
working_dir: "results/working"
# Directory to store final results (count matrix, summary reports)
results_dir: "results"


# Parameters used for each step of the workflow
params:
  fastqc:
    extra: ""
  bwa:
    # optional bwa aln parameters
    extra: "-n 0.02"
  cutadapt:
    # parameters
    params: "--adapter='CTGTAGGCACCATCAATATCTCGTATGCCGTCTTCTGCTTG' "
  plastid:
    # `offset` is obtained after running "mito_readphasing_metagene.snakefile"
    offset: 15
    min_length: 15
    max_length: 45
    mapping_function: "threeprime"
